(ns clj-kondo-fix.impl.fixes
  "Aggregator namespace. Requires all per-rule fix namespaces and re-exports
   each fix-*-in-file function so that rules.clj and core_test.clj can
   continue to reference clj-kondo-fix.impl.fixes/fix-* without change."
  (:require [clj-kondo-fix.impl.fixes.unused-namespace    :as unused-namespace]
            [clj-kondo-fix.impl.fixes.duplicate-require   :as duplicate-require]
            [clj-kondo-fix.impl.fixes.unused-binding      :as unused-binding]
            [clj-kondo-fix.impl.fixes.unused-import       :as unused-import]
            [clj-kondo-fix.impl.fixes.unused-referred-var :as unused-referred-var]
            [clj-kondo-fix.impl.fixes.missing-else-branch :as missing-else-branch]
            [clj-kondo-fix.impl.fixes.misplaced-docstring :as misplaced-docstring]
            [clj-kondo-fix.impl.fixes.unused-private-var  :as unused-private-var]
            [clj-kondo-fix.impl.fixes.redundant-call      :as redundant-call]
            [clj-kondo-fix.impl.fixes.redundant-do        :as redundant-do]
            [clj-kondo-fix.impl.fixes.redundant-let       :as redundant-let]
            [clj-kondo-fix.impl.fixes.redundant-str-call  :as redundant-str-call]
            [clj-kondo-fix.impl.fixes.redundant-format   :as redundant-format]
            [clj-kondo-fix.impl.fixes.redundant-fn-wrapper :as redundant-fn-wrapper]
            [clj-kondo-fix.impl.fixes.redundant-nested-call :as redundant-nested-call]
            [clj-kondo-fix.impl.fixes.redundant-primitive-coercion :as redundant-primitive-coercion]
            [clj-kondo-fix.impl.fixes.if-x-x-y           :as if-x-x-y]
            [clj-kondo-fix.impl.fixes.if-nil-return      :as if-nil-return]
            [clj-kondo-fix.impl.fixes.keyword-binding    :as keyword-binding]
            [clj-kondo-fix.impl.fixes.not-nil            :as not-nil]
            [clj-kondo-fix.impl.fixes.condition-always-true :as condition-always-true]
            [clj-kondo-fix.impl.fixes.docstring-leading-trailing-whitespace :as docstring-leading-trailing-whitespace]
            [clj-kondo-fix.impl.fixes.equals-nil          :as equals-nil]
            [clj-kondo-fix.impl.fixes.equals-true         :as equals-true]
            [clj-kondo-fix.impl.fixes.equals-false        :as equals-false]
            [clj-kondo-fix.impl.fixes.equals-float       :as equals-float]
            [clj-kondo-fix.impl.fixes.plus-one           :as plus-one]
            [clj-kondo-fix.impl.fixes.minus-one          :as minus-one]
            [clj-kondo-fix.impl.fixes.single-logical-operand :as single-logical-operand]
             [clj-kondo-fix.impl.fixes.single-key-in      :as single-key-in]
              [clj-kondo-fix.impl.fixes.cond-else       :as cond-else]
              [clj-kondo-fix.impl.fixes.docstring-blank  :as docstring-blank]
              [clj-kondo-fix.impl.fixes.redundant-declare :as redundant-declare]
              [clj-kondo-fix.impl.fixes.uninitialized-var :as uninitialized-var]
              [clj-kondo-fix.impl.fixes.dynamic-var-not-earmuffed :as dynamic-var-not-earmuffed]
              [clj-kondo-fix.impl.fixes.earmuffed-var-not-dynamic :as earmuffed-var-not-dynamic]
              [clj-kondo-fix.impl.fixes.equals-expected-position :as equals-expected-position]
              [clj-kondo-fix.impl.fixes.redundant-let-binding :as redundant-let-binding]
               [clj-kondo-fix.impl.fixes.unsorted-imports :as unsorted-imports]
                [clj-kondo-fix.impl.fixes.unsorted-required-namespaces :as unsorted-required-namespaces]
                [clj-kondo-fix.impl.fixes.unused-alias :as unused-alias]
                [clj-kondo-fix.impl.fixes.alias-same-as-ns :as alias-same-as-ns]
                [clj-kondo-fix.impl.fixes.duplicate-refer :as duplicate-refer]
                [clj-kondo-fix.impl.fixes.unused-excluded-var :as unused-excluded-var]
                [clj-kondo-fix.impl.fixes.unresolved-excluded-var :as unresolved-excluded-var]
                [clj-kondo-fix.impl.fixes.single-operand-comparison :as single-operand-comparison]
                [clj-kondo-fix.impl.fixes.java-static-field-call :as java-static-field-call]
                [clj-kondo-fix.impl.fixes.duplicate-set-key :as duplicate-set-key]
                [clj-kondo-fix.impl.fixes.def-fn :as def-fn]
                [clj-kondo-fix.impl.fixes.aliased-namespace-symbol :as aliased-ns-sym]
                [clj-kondo-fix.impl.fixes.is-message-not-string :as is-msg-not-str]
                [clj-kondo-fix.impl.fixes.non-arg-vec-return-type-hint :as non-arg-hint]))

(def fix-unused-ns-in-file          unused-namespace/fix-unused-ns-in-file)
(def fix-duplicate-require-in-file  duplicate-require/fix-duplicate-require-in-file)
(def fix-unused-binding-in-file     unused-binding/fix-unused-binding-in-file)
(def fix-unused-import-in-file      unused-import/fix-unused-import-in-file)
(def fix-unused-referred-var-in-file unused-referred-var/fix-unused-referred-var-in-file)
(def fix-missing-else-branch-in-file missing-else-branch/fix-missing-else-branch-in-file)
(def fix-misplaced-docstring-in-file misplaced-docstring/fix-misplaced-docstring-in-file)
(def fix-unused-private-var-in-file  unused-private-var/fix-unused-private-var-in-file)
(def fix-redundant-call-in-file      redundant-call/fix-redundant-call-in-file)
(def fix-redundant-do-in-file        redundant-do/fix-redundant-do-in-file)
(def fix-redundant-let-in-file       redundant-let/fix-redundant-let-in-file)
(def fix-equals-nil-in-file          equals-nil/fix-equals-nil-in-file)
(def fix-equals-true-in-file         equals-true/fix-equals-true-in-file)
(def fix-equals-false-in-file        equals-false/fix-equals-false-in-file)
(def fix-equals-float-in-file       equals-float/fix-equals-float-in-file)
(def fix-plus-one-in-file           plus-one/fix-plus-one-in-file)
(def fix-minus-one-in-file          minus-one/fix-minus-one-in-file)
(def fix-single-logical-operand-in-file single-logical-operand/fix-single-logical-operand-in-file)
(def fix-single-key-in-in-file          single-key-in/fix-single-key-in-in-file)
(def fix-redundant-str-call-in-file     redundant-str-call/fix-redundant-str-call-in-file)
(def fix-redundant-format-in-file      redundant-format/fix-redundant-format-in-file)
(def fix-redundant-fn-wrapper-in-file redundant-fn-wrapper/fix-redundant-fn-wrapper-in-file)
(def fix-redundant-nested-call-in-file redundant-nested-call/fix-redundant-nested-call-in-file)
(def fix-redundant-primitive-coercion-in-file redundant-primitive-coercion/fix-redundant-primitive-coercion-in-file)
(def fix-if-x-x-y-in-file              if-x-x-y/fix-if-x-x-y-in-file)
(def fix-if-nil-return-in-file         if-nil-return/fix-if-nil-return-in-file)
(def fix-keyword-binding-in-file      keyword-binding/fix-keyword-binding-in-file)
(def fix-not-nil-in-file              not-nil/fix-not-nil-in-file)
(def fix-condition-always-true-in-file condition-always-true/fix-condition-always-true-in-file)
(def fix-docstring-leading-trailing-whitespace-in-file docstring-leading-trailing-whitespace/fix-docstring-leading-trailing-whitespace-in-file)
(def fix-cond-else-in-file              cond-else/fix-cond-else-in-file)
(def fix-docstring-blank-in-file        docstring-blank/fix-docstring-blank-in-file)
(def fix-redundant-declare-in-file      redundant-declare/fix-redundant-declare-in-file)
(def fix-uninitialized-var-in-file     uninitialized-var/fix-uninitialized-var-in-file)
(def fix-dynamic-var-not-earmuffed-in-file dynamic-var-not-earmuffed/fix-dynamic-var-not-earmuffed-in-file)
(def fix-earmuffed-var-not-dynamic-in-file earmuffed-var-not-dynamic/fix-earmuffed-var-not-dynamic-in-file)
(def fix-equals-expected-position-in-file equals-expected-position/fix-equals-expected-position-in-file)
(def fix-redundant-let-binding-in-file redundant-let-binding/fix-redundant-let-binding-in-file)
(def fix-unsorted-imports-in-file unsorted-imports/fix-unsorted-imports-in-file)
(def fix-unsorted-required-namespaces-in-file unsorted-required-namespaces/fix-unsorted-required-namespaces-in-file)
(def fix-unused-alias-in-file unused-alias/fix-unused-alias-in-file)
(def fix-alias-same-as-ns-in-file alias-same-as-ns/fix-alias-same-as-ns-in-file)
(def fix-duplicate-refer-in-file duplicate-refer/fix-duplicate-refer-in-file)
(def fix-unused-excluded-var-in-file unused-excluded-var/fix-unused-excluded-var-in-file)
(def fix-unresolved-excluded-var-in-file unresolved-excluded-var/fix-unresolved-excluded-var-in-file)
(def fix-single-operand-comparison-in-file single-operand-comparison/fix-single-operand-comparison-in-file)
(def fix-java-static-field-call-in-file java-static-field-call/fix-java-static-field-call-in-file)
(def fix-duplicate-set-key-in-file duplicate-set-key/fix-duplicate-set-key-in-file)
(def fix-def-fn-in-file def-fn/fix-def-fn-in-file)
(def fix-aliased-namespace-symbol-in-file aliased-ns-sym/fix-aliased-namespace-symbol-in-file)
(def fix-is-message-not-string-in-file is-msg-not-str/fix-is-message-not-string-in-file)
(def fix-non-arg-vec-return-type-hint-in-file non-arg-hint/fix-non-arg-vec-return-type-hint-in-file)
